### ISSUE TITLE
I love this repo

### ISSUE THREAD

**Issue by izaakf** [sentriz/fish-pipenv#26]

**Comment by kennethreitz** [comment]
@izaakf you may kindly fuck yourself?

**Comment by franciscolourenco** [comment]
@izaakf could you please elaborate?

**Comment by izaakf** [comment]
> @izaakf could you please elaborate?

what would you like me to elaborate on? I feel this is rather clear.

**Comment by franciscolourenco** [comment]
Just wanted to know why you thought think repo was stupid. Since then I've found out that virtualenv now also provides a fish activation script, and I've settled for a different solution, so I don't care anymore.

Here is it in case anyone else is interested:

```fish
    #~/.config/fish/config.fish

    # python virtualenv auto load when changing directory.
    # note: this assumes a virtualenv was created and stored in the project directory with: `virtualenv .venv`
    function auto_virtualenv --on-variable PWD
        if test -d ".venv"
            if not set -q VIRTUAL_ENV
                set --export --global venv_root $PWD
                source .venv/bin/activate.fish
            end
        else
            if set -q VIRTUAL_ENV
                if set -q venv_root
                    if not string match --entire --quiet $venv_root $PWD
                        set --erase venv_root
                        deactivate
                    end
                end
            end
        end
    end

    # in case the shell is started in a directory which contains a virtualenv
    auto_virtualenv
```

**Comment by izaakf** [comment]
I thought this repo was stupid because I was red pilled by @kennethreitz

Though, after some heavier investigation I realised that this was in fact a great repo. Thanks for including your script I will be sure to use it my dear friend. @franciscolourenco may I ask what you think of this repo? If it is not too personal a question.

**Comment by franciscolourenco** [comment]
~@izaakf did @kennethreitz complain about this project?~
Only now noticed this 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/208149/196215793-f07d1e21-d594-4645-a447-e74c28542f1a.png">

**Comment by franciscolourenco** [comment]
@izaakf I dismissed this plugin as a viable choice once I found at least two unresolved issues previously closed (but now re-opened) due to inactivity:

1. https://github.com/sentriz/fish-pipenv/issues/20#issuecomment-463627715
2. https://github.com/sentriz/fish-pipenv/issues/19#issuecomment-463627616

**Comment by franciscolourenco** [comment]
Regarding [Pipenv](https://pipenv.pypa.io/en/latest/) in general, I gave it a try as well as I did with [Poetry](https://python-poetry.org/). It seems that the community hasn't settled for wither, both projects still seem to have some rough edges, and I didn't need any package management functionality for the time being, so I stuck with vanilla virtualenv once I found out it supported fish now.

**Comment by izaakf** [comment]
@kennethreitz complained about me for having an opinion which I find bizarre. It's okay though as I have educated myself on the history of this project. It's fascinating how one small project can have such a profound impact on developers around the world. That's why I fell in love with this project

**Comment by izaakf** [comment]
I understand your dismissal of this plugin due to those open issues. It is a shame they were never resolved and closed due to staleness. If I had the cycles I most certainly would've sought to resolve them myself. If I find the cycles to work on those tasks do you think you would return to use this project @franciscolourenco?

**Comment by izaakf** [comment]
I see, I'm still an avid user of Poetry myself. Despite the lack of community there is still something magical, and whimsical about it. I have been trying to advocate for use of Poetry within crypto and NFT communities as I think they could be easily persuaded to use such a technology. It has been with little success thus far but I feel that with upcoming global events that those in the crypto could still be encouraged to use Poetry.

**Comment by franciscolourenco** [comment]
> It's fascinating how one small project can have such a profound impact on developers around the world. That's why I fell in love with this project

I've heard about, and read some interesting blog posts by [kennethreitz](https://github.com/kennethreitz), but I'm not sure I actually know what you are talking about. However I'm curious to find out :)

> If I find the cycles to work on those tasks do you think you would return to use this project @franciscolourenco?

I think I would, if Pipenv works without problems, why not.

> I see, I'm still an avid user of Poetry myself

Do you use Poetry instead of Pipenv at the moment?

**Comment by izaakf** [comment]
Hi @franciscolourenco wonderful to hear from you again my dear friend. I do not use poetry these days as it is stupid. Thanks for asking. I still love fish-pipenv though! kudos to @sentriz for creating and maintaining this wonderful piece of software!
