### ISSUE TITLE
Does this work with Oh my Fish?

### ISSUE THREAD

**Issue by domoritz** [sentriz/fish-pipenv#28]
I installed this plugin with OMF `omf install https://github.com/sentriz/fish-pipenv` but it doesn't load the virtual env when I cd into a repo with a `Pipfile`. Does it work for you?

**Comment by sentriz** [comment]
can this be closed now?

**Comment by domoritz** [comment]
I just provided the installation instructions in the PR but it's not working for me as expected. Can you give it a try?

**Comment by sentriz** [comment]
sorry I misread. it is working for me with [fundle](https://github.com/danhper/fundle). let me try omf

**Comment by domoritz** [comment]
Thanks!

**Comment by sentriz** [comment]
tested out omf in a container.
it looks like maybe omf doesn't recognise the `conf.d` layout of this plugin. eg. it works if you symlink `~/.local/share/omf/pkg/fish-pipenv/conf.d/pipenv.fish` to `~/.local/share/omf/pkg/fish-pipenv/init.fish`.
so I wonder if there is a layout we could use that both omf plus fisher/fundle/etc understand

**Comment by sentriz** [comment]
it looks like just having an `init.fish` in the root of this repo will work for 
- [x] oh my fish
- [x] fundle
- [x] fisher
- [ ] are there more?

**Comment by domoritz** [comment]
I think https://github.com/oh-my-fish/oh-my-fish is pretty popular. It would be super sweet if it was supported. I'm not aware of any other popular fish plugin managers.

**Comment by sentriz** [comment]
ok for the meantime I've moved to `init.fish`. can you try uninstall what you currently have and try that `omf install` command again? (or maybe an upgrade might work) and `exec fish`

**Comment by domoritz** [comment]
Hmm, maybe I'm holding it wrong but it doesn't seem to work for me.

```
> omf install https://github.com/sentriz/fish-pipenv
> ls dir
Pipfile Pipfile.lock
> cd dir
... nothing happens
```

**Comment by sentriz** [comment]
did you `exec fish` after the omf install?

**Comment by domoritz** [comment]
Yes

**Comment by sentriz** [comment]
strange. it's working for me. can you `ls ~/.local/share/omf/pkg/fish-pipenv/`?
also for me it didn't work straight away. had to do a `$ cd ..; cd -` once or twice

**Comment by domoritz** [comment]
```
> ls ~/.local/share/omf/pkg/fish-pipenv/                                                                                                                                               
README.md init.fish
```

**Comment by domoritz** [comment]
I must be doing something wrong because it also doesn't work for me if I use fisher. I'll reinstall some things and see what happens.

**Comment by sentriz** [comment]
here it seems to be working a fresh alpine docker

```
manjaro, ~, sudo docker run -it alpine /bin/sh
/ # apk add python3 fish curl git
OK: 95 MiB in 36 packages
/ # pip3 install --user pipenv
Collecting pipenv
Successfully installed certifi-2019.9.11 pipenv-2018.11.26 virtualenv-16.7.5 virtualenv-clone-0.5.3
/ # exec fish
Welcome to fish, the friendly interactive shell
root@9f06f765deba /# curl -L https://get.oh-my.fish | fish
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package default
✔ default successfully installed.
Installation successful!
Welcome to fish, the friendly interactive shell
⋊> / set -U fish_user_paths ~/.local/bin $fish_user_paths
⋊> / cd
⋊> ~ mkdir testrepo
⋊> ~ cd testrepo/
⋊> ~/testrepo pipenv install
Pipfile: /root/testrepo/Pipfile
Using /usr/bin/python3.7 (3.7.3) to create virtualenv…
⠦ Creating virtual environment...Already using interpreter /usr/bin/python3.7
Installing setuptools, pip, wheel...
done.
✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/testrepo-kSern7h6
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
⋊> ~/testrepo cd
⋊> ~ omf install https://github.com/sentriz/fish-pipenv
✔ fish-pipenv successfully installed.
⋊> ~ ll ~/.local/share/omf/pkg/fish-pipenv/
total 8K     
-rw-r--r--    1 root     root        2.8K Sep 18
-rw-r--r--    1 root     root        1.3K Sep 18
⋊> ~ exec fish
⋊> ~ cd testrepo/
Launching subshell in virtual environment…
Welcome to fish, the friendly interactive shell
⋊> ~/testrepo  source /root/.local/share/virtualenvs/testrepo-kSern7h6/bin/activate.fish
(testrepo) ⋊> ~/testrepo echo $VIRTUAL_ENV
/root/.local/share/virtualenvs/testrepo-kSern7h6
(testrepo) ⋊> ~/testrepo cd
⋊> ~ echo $VIRTUAL_ENV

⋊> ~   
```

**Comment by domoritz** [comment]
Ah, looks like my mistake was in the testfolder. My Pipfile was corrupted. It works for me now. Thanks for bearing with me and thanks for the plugin!

**Comment by domoritz** [comment]
Ah, not corrupted. I just didn't have a virtual environment yet. 🤦‍♂

**Comment by jorgebucaran** [comment]
Note: Fisher instructions should be `fisher install sentriz/fish-pipenv`. 😄 @domoritz
